/**
 * Deterministic tutorial renderer (modeling-tutorial spec, workstream 1).
 *
 * Renders a loaded tutorial to one Markdown document. Pure: same steps
 * and snapshots produce byte-identical output. Each step renders
 * motivation first (learning-design C5: generate before the canonical
 * answer), then the concept, then the model-so-far's verbalization,
 * then the builds-on/unlocks links and the deck/gym callouts.
 *
 * For a "counterexample" step the hook is generated here from the
 * step's model: the minimal population its named constraint forbids --
 * exactly what the prior step's model still allowed. Two build-time
 * honesty checks keep the narrative true: the named constraint must not
 * yet exist in the prior step's model (the step genuinely introduces
 * it), and every step's snapshot must pass validation with no errors
 * (the learner never ends a step on a broken model).
 */
import { type Constraint, type FactType, type OrmModel, ValidationEngine } from "@barwise/core";
import { generateCounterexampleForConstraint } from "@barwise/core/counterexample";
import { Verbalizer } from "@barwise/core/verbalization";
import type { LoadedTutorial, LoadedTutorialStep } from "./types.js";

/** Thrown when a tutorial cannot be rendered truthfully. */
export class TutorialRenderError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TutorialRenderError";
  }
}

export interface RenderTutorialOptions {
  /** Tool version stamped into the header (passed in to keep the renderer pure). */
  readonly toolVersion: string;
}

const verbalizer = new Verbalizer();
const validator = new ValidationEngine();

/** Render a loaded tutorial to Markdown. */
export function renderTutorial(tutorial: LoadedTutorial, options: RenderTutorialOptions): string {
  const stepTitles = new Map(tutorial.steps.map((s, i) => [s.id, `Step ${i + 1}: ${s.title}`]));

  const parts: string[] = [];
  parts.push(renderHeader(tutorial, options.toolVersion));

  tutorial.steps.forEach((step, i) => {
    const prior = i > 0 ? tutorial.steps[i - 1]!.modelInstance : undefined;
    parts.push(renderStep(step, i + 1, prior, stepTitles));
  });

  parts.push(renderClosing(tutorial));
  // Collapse runs of blank lines so optional sections never leave gaps.
  return parts.join("\n").replace(/\n{3,}/g, "\n\n");
}

function renderHeader(tutorial: LoadedTutorial, toolVersion: string): string {
  return `# ${tutorial.title}

> Generated by barwise ${toolVersion} (\`npm run regen:tutorial\`). Do not
> edit this file by hand: edit the tutorial source and regenerate.

**Serves the transition:** ${tutorial.transition.from} to ${tutorial.transition.to}.
**Exit performance:** ${tutorial.exitPerformance}

A note before you start: each step shows you a *problem first* -- often a
concrete population the model-so-far wrongly allows -- and only then the
concept that fixes it. Try to name the fix yourself before reading on.
This feels harder than reading definitions; it is meant to. If you have
modeled in ER or relational schemas before, start here anyway -- the
early steps are where those habits mislead.

${tutorial.intro}
`;
}

function renderStep(
  step: LoadedTutorialStep,
  number: number,
  prior: OrmModel | undefined,
  stepTitles: ReadonlyMap<string, string>,
): string {
  const model = step.modelInstance;
  assertValidSnapshot(step, model);

  const lines: string[] = [];
  lines.push(`## Step ${number}: ${step.title}`);
  lines.push("");
  lines.push(`*CSDP step ${step.csdpStep}.*`);
  lines.push("");

  if (step.buildsOn.length > 0) {
    lines.push(`Builds on: ${step.buildsOn.map((id) => linkTo(id, stepTitles)).join(", ")}.`);
  }

  lines.push("");
  lines.push("### The problem");
  lines.push("");
  lines.push(renderMotivation(step, prior));
  lines.push("");
  lines.push("### The concept");
  lines.push("");
  lines.push(step.concept.trim());
  lines.push("");
  lines.push("### The model so far");
  lines.push("");
  lines.push("```");
  for (const v of verbalizer.verbalizeModel(model)) {
    lines.push(v.text);
  }
  lines.push("```");
  lines.push("");

  const callouts: string[] = [];
  if (step.unlocks.length > 0) {
    callouts.push(`Unlocks: ${step.unlocks.map((id) => linkTo(id, stepTitles)).join(", ")}.`);
  }
  if (step.deck) {
    callouts.push(`Drill this: deck subdeck \`${step.deck}\`.`);
  }
  if (step.gym) {
    callouts.push(`Practice this: gym exercise \`${step.gym}\`.`);
  }
  if (callouts.length > 0) {
    lines.push(callouts.join("\n"));
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * The motivation block. For a counterexample step, generate the
 * forbidden population from this step's model and verify the story:
 * the constraint is new in this step (absent from the prior model).
 */
function renderMotivation(step: LoadedTutorialStep, prior: OrmModel | undefined): string {
  if (step.motivation.kind === "prose") {
    return step.motivation.text.trim();
  }

  const constraintId = step.motivation.constraintId;
  const found = findConstraint(step.modelInstance, constraintId);
  if (!found) {
    throw new TutorialRenderError(
      `step "${step.id}": constraint "${constraintId}" not found in its model snapshot`,
    );
  }
  if (prior && findConstraint(prior, constraintId)) {
    throw new TutorialRenderError(
      `step "${step.id}": constraint "${constraintId}" already exists in the prior `
        + `step's model -- the motivation would be false`,
    );
  }

  const ce = generateCounterexampleForConstraint(
    found.constraint,
    found.factType,
    step.modelInstance,
  );
  if (!ce) {
    throw new TutorialRenderError(
      `step "${step.id}": no counterexample could be generated for "${constraintId}" `
        + `(constraint type "${found.constraint.type}")`,
    );
  }

  return `Until this step, nothing in the model forbids the following
population -- the tool derives it mechanically from the constraint you
are about to add:

> ${ce.text}

*(motivation generated from the model)*`;
}

function assertValidSnapshot(step: LoadedTutorialStep, model: OrmModel): void {
  const errors = validator.errors(model);
  if (errors.length > 0) {
    throw new TutorialRenderError(
      `step "${step.id}": its model snapshot has validation errors:\n`
        + errors.map((e) => `  - ${e.message}`).join("\n"),
    );
  }
}

function findConstraint(
  model: OrmModel,
  constraintId: string,
): { constraint: Constraint; factType: FactType; } | undefined {
  for (const ft of model.factTypes) {
    for (const c of ft.constraints) {
      if (c.id === constraintId) {
        return { constraint: c, factType: ft };
      }
    }
  }
  return undefined;
}

function linkTo(id: string, stepTitles: ReadonlyMap<string, string>): string {
  const title = stepTitles.get(id);
  if (!title) return id;
  return `[${title}](#${anchor(title)})`;
}

/** GitHub-style heading anchor. */
function anchor(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "")
    .replace(/ /g, "-");
}

function renderClosing(tutorial: LoadedTutorial): string {
  return `## Where to go next

The tutorial motivates and sequences; it does not replace the method's
own text. Halpin & Morgan, *Information Modeling and Relational
Databases* (2nd ed.), chapters 3-7, teach the CSDP in full.

The three learning artifacts are one system: this tutorial motivates
(why, and in what order), the Anki deck retains (\`docs/anki/\`), and
the modeling gym applies (\`packages/learn/exercises/\`). Steps above
link to the subdeck to drill and the exercise to attempt. Your next
move: open the gym and model ${tutorial.transition.to}-level exercises
unaided -- generation, not re-reading, is what moves you along the
scale.
`;
}
